services:
  api:
    build: .
    ports:
      - 80:80/tcp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: 
      - '.env'
    restart: unless-stopped
  doc:
    image: redocly/redoc
    ports:
      - 8080:80/tcp
    environment:
      SPEC_URL: swagger.yaml
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/swagger.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env' 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
volumes:
  postgres: