services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: 
      - .env
  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env' 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "node", "-d", "erp"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres: