CREATE TABLE starred_problem (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id        TEXT NOT NULL,
    problem_id     INT NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES account (id),
    FOREIGN KEY (problem_id) REFERENCES problem (id),
    UNIQUE (user_id, problem_id)
);

CREATE TABLE starred_solution (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id        TEXT NOT NULL,
    solution_id    INT NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES account (id),
    FOREIGN KEY (solution_id) REFERENCES solution (id),
    UNIQUE (user_id, solution_id)
);

CREATE TABLE starred_submission (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id        TEXT NOT NULL,
    submission_id  UUID NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT NOW(),

    FOREIGN KEY (user_id) REFERENCES account (id),
    FOREIGN KEY (submission_id) REFERENCES submission (id),
    UNIQUE (user_id, submission_id)
);
