name: Deploy Kadane-Backend schemas to Amazon RDS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/sql/schemas/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Lambda Environment Variables
        run: |
          aws lambda update-function-configuration \
            --function-name schema-deployer \
            --environment "Variables={
                DB_HOST=${{ secrets.AWS_DB_HOST }},
                DB_PORT=${{ secrets.AWS_DB_PORT }},
                DB_USER=${{ secrets.AWS_DB_USER }},
                DB_PASSWORD=${{ secrets.AWS_DB_PASSWORD }},
                DB_NAME=${{ secrets.AWS_DB_NAME }},
            }"
          
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: src/sql/schemas/**
      
      - name: Invoke Lambda
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            aws lambda invoke \
              --function-name ${{ vars.AWS_BACKEND_DB_LAMBDA_FUNCTION }} \
              --payload "{\"schema_file\": \"$file\"}" \
              --cli-binary-format raw-in-base64-out \
              response.json
          done